In [1]:
import numpy as np
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [2]:
np.sum(ar3)#sum of all numbers in matrix

1225

In [3]:
np.sum(ar3,axis=0)#it adds the matrix numbers in column wise

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [4]:
np.sum(ar3,axis=1)#ti adds the matrix numbers in row wise

array([ 45, 145, 245, 345, 445])

In [5]:
# mean-->average value
# median-->center value
# mode--> max num of repeated element
# variance-->median/total num of elements
#std-->square root of varience

In [6]:
np.linspace(1,10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [7]:
#random module
#to generate random number between the range
#np.random.randint(start,end)
np.random.randint(40)

25

In [8]:
np.random.randint(20,30,3)

array([29, 21, 28])

In [10]:
#rand ()-->
#to get the randomly generated values from 0 to 1, based on uniform distribution
np.random.rand(4)

array([0.4144608 , 0.46596138, 0.34371197, 0.22467888])

In [11]:
np.linespace(1,10,5,retstep=True)

AttributeError: module 'numpy' has no attribute 'linespace'

In [ ]:
#pandas
#import pandas as pd
