In [2]:
import numpy as np
ar1=np.arange(13)
ar1
len(ar1)

13

In [3]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [7]:
# Identify matrix can be created using 2 functions
# eye() --> used to define both user defined rows and columns
# identify() --> used to define same number of rows and columns
# syntax --> np.eye(5) --> 5 is 5 rows and 5 columns
# syntax --> np.eye(3,4) --> 3 rows and 4 columns
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
# To perform multidimensional slicing
ar2 = np.arange(25).reshape(5,5)
# ar2[rows,columns,step]

# ar2[row_start,row_end,col_start,col_end, step]
ar2[0:5, 0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [12]:
ar2[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
ar2[0:0,0:0]

array([], shape=(0, 0), dtype=int32)

In [16]:
ar2[-5:-3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
ar2[-3:-2]

array([[10, 11, 12, 13, 14]])

In [22]:
ar2[-4:-2,-5:-3]

array([[ 5,  6],
       [10, 11]])