In [3]:
import numpy as np
arr = np.array([[1,2,3],[45,6,78],[89,90,6]])
print("original array", arr)

original array [[ 1  2  3]
 [45  6 78]
 [89 90  6]]


In [4]:
na =np.array([1,2,3])
na
# new_arr = np.r_[arr,[np]]
# print("New array", new_arr)

array([1, 2, 3])

In [5]:
na = np.array([12,23,34])
new_arr = np.r_[arr,[na]]
print("new array",new_arr)

new array [[ 1  2  3]
 [45  6 78]
 [89 90  6]
 [12 23 34]]


In [6]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A  0.692809 -0.213793 -1.473833 -0.544031
B  0.165339  1.362578 -0.263194 -0.886454
C  0.667956  0.422170 -1.474880  1.360809
D -0.441552  0.255984  0.362250 -1.185824
E  1.383531 -1.121027  0.906969  0.141841

In [7]:
df.loc['A']#ACESSING THE ROWS

W    0.692809
X   -0.213793
Y   -1.473833
Z   -0.544031
Name: A, dtype: float64

In [8]:
df.loc[['A','B']]

W         X         Y         Z
A  0.692809 -0.213793 -1.473833 -0.544031
B  0.165339  1.362578 -0.263194 -0.886454

In [9]:
#TO ACESS THE ROWS WITH INDEX
df.iloc[3]

W   -0.441552
X    0.255984
Y    0.362250
Z   -1.185824
Name: D, dtype: float64

In [10]:
#to get the specific value of co-ordinate in a valueframe
df.loc['B','Y']

-0.2631944278064065

In [11]:
#TO GET MULTIPLE CO-ORDINATES
df.loc[['A','B'],['W','X']]#df.loc[['rows'],['cols']]

W         X
A  0.692809 -0.213793
B  0.165339  1.362578

In [12]:
#retrive the data based on condition
df

W         X         Y         Z
A  0.692809 -0.213793 -1.473833 -0.544031
B  0.165339  1.362578 -0.263194 -0.886454
C  0.667956  0.422170 -1.474880  1.360809
D -0.441552  0.255984  0.362250 -1.185824
E  1.383531 -1.121027  0.906969  0.141841

In [13]:
df>0#values greater than 0

W      X      Y      Z
A   True  False  False  False
B   True   True  False  False
C   True   True  False   True
D  False   True   True  False
E   True  False   True   True

In [14]:
df[df>0]

W         X         Y         Z
A  0.692809       NaN       NaN       NaN
B  0.165339  1.362578       NaN       NaN
C  0.667956  0.422170       NaN  1.360809
D       NaN  0.255984  0.362250       NaN
E  1.383531       NaN  0.906969  0.141841

In [15]:
df['W']>0

A     True
B     True
C     True
D    False
E     True
Name: W, dtype: bool

In [16]:
df[df['W']>0]

W         X         Y         Z
A  0.692809 -0.213793 -1.473833 -0.544031
B  0.165339  1.362578 -0.263194 -0.886454
C  0.667956  0.422170 -1.474880  1.360809
E  1.383531 -1.121027  0.906969  0.141841

In [17]:
#to handle the missing datas
df

W         X         Y         Z
A  0.692809 -0.213793 -1.473833 -0.544031
B  0.165339  1.362578 -0.263194 -0.886454
C  0.667956  0.422170 -1.474880  1.360809
D -0.441552  0.255984  0.362250 -1.185824
E  1.383531 -1.121027  0.906969  0.141841

In [18]:
d={'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[6,7,8],'D':[np.nan,np.nan,np.nan]}
df1=pd.DataFrame(d)
df1

A    B  C   D
0  1.0  5.0  6 NaN
1  2.0  NaN  7 NaN
2  NaN  NaN  8 NaN

In [19]:
#to drop the values with nan
#dropna
df1.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [20]:
df

W         X         Y         Z
A  0.692809 -0.213793 -1.473833 -0.544031
B  0.165339  1.362578 -0.263194 -0.886454
C  0.667956  0.422170 -1.474880  1.360809
D -0.441552  0.255984  0.362250 -1.185824
E  1.383531 -1.121027  0.906969  0.141841

In [21]:
#dropna(how,thresh, axis,inplace)
#how='all'or'any'
df1.dropna(how='all')#it will be checking the rows with all nan values to delete the row

A    B  C   D
0  1.0  5.0  6 NaN
1  2.0  NaN  7 NaN
2  NaN  NaN  8 NaN

In [22]:
df1.dropna(how='any')#it will delete the row there is one nan in a row

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [23]:
df1.dropna(how='all',axis=1)#to delete the col if it present all nan's in col

A    B  C
0  1.0  5.0  6
1  2.0  NaN  7
2  NaN  NaN  8

In [24]:
df1.dropna(how='any',axis=1)#to delete the col if there is even one nan in that col

C
0  6
1  7
2  8

In [25]:
#to check the sum of nan values in each row
df1.isna()

A      B      C     D
0  False  False  False  True
1  False   True  False  True
2   True   True  False  True

In [26]:
df1.isna().sum()

A    1
B    2
C    0
D    3
dtype: int64

In [27]:
#thresh
df1.dropna(thresh=2)

A    B  C   D
0  1.0  5.0  6 NaN
1  2.0  NaN  7 NaN

In [28]:
#fillna()
df1.fillna(value=0)# it fill the nan values with the given number

A    B  C    D
0  1.0  5.0  6  0.0
1  2.0  0.0  7  0.0
2  0.0  0.0  8  0.0

In [29]:
df1['A'].fillna(value=df1['A'].mean())#to print the nan value by calculating the mean value

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [30]:
#group by
#to group based on col and perform aggregate functions
data={'company':['Google','Google','Meta','Meta','Fb','Fb'],
      'person':['sam','mani','sai','prashanth','mohan','mounika'],
      'sales':[300,500,100,200,600,900]}
df2=pd.DataFrame(data)
df2

company     person  sales
0  Google        sam    300
1  Google       mani    500
2    Meta        sai    100
3    Meta  prashanth    200
4      Fb      mohan    600
5      Fb    mounika    900

In [31]:
bycomp=df2.groupby("company")
bycomp

bycomp.sum()

bycomp.sum()

In [32]:
bycomp.sum()

person  sales
company                     
Fb       mohanmounika   1500
Google        sammani    800
Meta     saiprashanth    300

In [33]:
df2['company'].value_counts()

company
Google    2
Meta      2
Fb        2
Name: count, dtype: int64

In [34]:
#to get the maximum salary of a person from each company
bycomp.max()

person  sales
company                
Fb       mounika    900
Google       sam    500
Meta         sai    200

In [35]:
bycomp['sales'].max()

company
Fb        900
Google    500
Meta      200
Name: sales, dtype: int64

In [36]:
#to get maximum salary person from each company
df2.loc[bycomp['sales'].idxmax()][['person','sales']]

person  sales
5    mounika    900
1       mani    500
3  prashanth    200

In [37]:
bycomp[['person','sales']].max()

person  sales
company                
Fb       mounika    900
Google       sam    500
Meta         sai    200

In [38]:
df=pd.read_csv("C:\\Users\\aparn\\OneDrive\\Desktop\\hackthon/samplecsv.csv")
df

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999   
1      2020                     Level 1                99999   
2      2020                     Level 1                99999   
3      2020                     Level 1                99999   
4      2020                     Level 1                99999   
...     ...                         ...                  ...   
37075  2013                     Level 3                 ZZ11   
37076  2013                     Level 3                 ZZ11   
37077  2013                     Level 3                 ZZ11   
37078  2013                     Level 3                 ZZ11   
37079  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
37075  Food product manufacturing          Percentage           H37   
37076  Food product manufacturing          Percentage           H38   
37077  Food product manufacturing          Percentage           H39   
37078  Food product manufacturing          Percentage           H40   
37079  Food product manufacturing          Percentage           H41   

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance   
1      Sales, government funding, grants and subsidies  Financial performance   
2                    Interest, dividends and donations  Financial performance   
3                                 Non-operating income  Financial performance   
4                                    Total expenditure  Financial performance   
...                                                ...                    ...   
37075                                      Quick ratio       Financial ratios   
37076              Margin on sales of goods for resale       Financial ratios   
37077                                 Return on equity       Financial ratios   
37078                           Return on total assets       Financial ratios   
37079                            Liabilities structure       Financial ratios   

         Value                             Industry_code_ANZSIC06  
0      733,258  ANZSIC06 divisions A-S (excluding classes K633...  
1      660,630  ANZSIC06 divisions A-S (excluding classes K633...  
2       54,342  ANZSIC06 divisions A-S (excluding classes K633...  
3       18,285  ANZSIC06 divisions A-S (excluding classes K633...  
4      654,872  ANZSIC06 divisions A-S (excluding classes K633...  
...        ...                                                ...  
37075       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37076       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37077       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37078        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
37079       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[37080 rows x 10 columns]

In [39]:
df2['company'].value_counts()

company
Google    2
Meta      2
Fb        2
Name: count, dtype: int64

In [40]:
#to get the maximum salary of a person from each company
bycomp.max()

person  sales
company                
Fb       mounika    900
Google       sam    500
Meta         sai    200

In [41]:
bycomp['sales'].max()

company
Fb        900
Google    500
Meta      200
Name: sales, dtype: int64

In [42]:
#to get maximum salary person from each company
df2.loc[bycomp['sales'].idxmax()][['person','sales']]

person  sales
5    mounika    900
1       mani    500
3  prashanth    200

In [43]:
bycomp[['person','sales']].max()

person  sales
company                
Fb       mounika    900
Google       sam    500
Meta         sai    200

In [45]:
names={"Name":'Abhi','Age':'age','City':'palce'}
df3=df2.rename(columns=names)